Pull Request for review
visva-dev/PROJECT-USING-BOOTSTRAP pull request #1
Opened 2020-06-16 15:11 UTC by visva-dev

## Microverse 7th project - Using Bootstrap
- This project requests students to build a replica of the news site Newsweek.com using the Bootstrap framework.
- Aligned all elements with Bootstrap and CSS.

2020-06-16 19:19 UTC, BrittanyBlake requested changes
### Status: Changes Required  🏗️ 🔨 
****
### Hello @visva-dev 👋 
You are doing a great job with this project! Your project looks amazing and you have done a wonderful job implementing the bootstrap classes!🎖️ 🌟 You are almost done. 💪  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****
### Navigation Bar

- [ ] The red background in the nav bar should extend to the width of the whole page.
The original page 👇 
![Screen Shot 2020-06-16 at 8 12 43 PM](https://user-images.githubusercontent.com/48804258/84811844-c25a9080-b00d-11ea-9d1d-b55ac5c98657.png)
Your clone 👇 
![Screen Shot 2020-06-16 at 8 04 56 PM](https://user-images.githubusercontent.com/48804258/84811743-96d7a600-b00d-11ea-86ca-503ac9dd74ce.png)

- [ ] The search icon in the nav links section is not aligned properly. There is too much space between the search and the icon. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-06-16 at 8 10 32 PM](https://user-images.githubusercontent.com/48804258/84812434-b3281280-b00e-11ea-8167-825701896bc6.png)
The original page 👇 
![Screen Shot 2020-06-16 at 8 10 39 PM](https://user-images.githubusercontent.com/48804258/84812437-b3c0a900-b00e-11ea-8fb2-88b9d49ac4c8.png)



- [ ] On the medium screen, the navigation links should disappear. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-06-16 at 8 05 49 PM](https://user-images.githubusercontent.com/48804258/84812599-eff40980-b00e-11ea-8540-f7b2b38f5c1e.png)
The original page 👇 
![Screen Shot 2020-06-16 at 8 05 57 PM](https://user-images.githubusercontent.com/48804258/84812604-f08ca000-b00e-11ea-8a91-411fd630cf54.png)

- [ ]The same should apply for the small screen. Please see the images below
Your clone 👇 
![Screen Shot 2020-06-16 at 8 06 10 PM](https://user-images.githubusercontent.com/48804258/84812811-45c8b180-b00f-11ea-9e3e-d42ed6e3b3e0.png)
The original page 👇 
![Screen Shot 2020-06-16 at 8 06 17 PM](https://user-images.githubusercontent.com/48804258/84812812-46614800-b00f-11ea-8d82-67a1de018135.png)

### Main content

- [ ] There is a horizontal scroll on the medium screen and too much white space on the right side of your clone. Please fix this.
![Screen Shot 2020-06-16 at 8 30 21 PM 1](https://user-images.githubusercontent.com/48804258/84813568-70673a00-b010-11ea-81c1-7fa0b7574259.png)

- [ ] There is also a horizontal scroll and extra white space on the right side on the small screen size. Please fix this. 
![Screen Shot 2020-06-16 at 8 33 03 PM](https://user-images.githubusercontent.com/48804258/84813782-c1772e00-b010-11ea-8680-9394a547fa50.png)

- [ ] On the medium screen of your clone, there is too much space between the images and the text on the opinion and the debate section. Please compare your clone with the original page and fix this.
Your clone 👇 
![Screen Shot 2020-06-16 at 8 35 38 PM](https://user-images.githubusercontent.com/48804258/84814713-28491700-b012-11ea-884c-0fbc81a3d396.png)
The original page 👇 
![Screen Shot 2020-06-16 at 8 35 47 PM](https://user-images.githubusercontent.com/48804258/84814719-2a12da80-b012-11ea-967f-212f00f72675.png)

- [ ] On the small screen size, the images and text in the opinion and debate section should remain in one line. Please compare your clone with the original page and fix this.
The original page 👇 
![Screen Shot 2020-06-16 at 8 45 30 PM](https://user-images.githubusercontent.com/48804258/84814903-74945700-b012-11ea-845a-7d25d97a993b.png)
Your clone 👇 
![Screen Shot 2020-06-16 at 8 45 37 PM](https://user-images.githubusercontent.com/48804258/84814907-752ced80-b012-11ea-989d-57aa289f8468.png)

- [ ] The articles in the "In the Magazine" section on the medium screen are currently occupying too much of the width causing a horizontal scroll. Additionally, the images are stretched in the medium screen and the title below the images should not wrap to a new line. Please compare your clone with the original page and fix this.
Your clone 👇 
![Screen Shot 2020-06-16 at 8 49 22 PM](https://user-images.githubusercontent.com/48804258/84815428-51b67280-b013-11ea-8e98-0c70476d6fb7.png)
The original page 👇 
![Screen Shot 2020-06-16 at 8 49 28 PM](https://user-images.githubusercontent.com/48804258/84815433-52e79f80-b013-11ea-88a0-b86feee16c19.png)

- [ ] The image tag `u.s.` on the article images in the "Editor's Pick" section on the medium and small screen sizes should remain in the bottom left corner of the image as it is on the large screen size. Please compare your clone with the original page and fix this. 

The original page 👇 
![Screen Shot 2020-06-16 at 8 54 29 PM](https://user-images.githubusercontent.com/48804258/84815896-fd5fc280-b013-11ea-8ead-2dc91b7aa147.png)
Your clone 👇 
![Screen Shot 2020-06-16 at 8 54 24 PM](https://user-images.githubusercontent.com/48804258/84815886-fa64d200-b013-11ea-85f3-880453401804.png)

- [ ] There is too much space between the side images and the text in the Featured slideshows section. Additionally, the side images should not be rounded.  
Your clone 👇 
![Screen Shot 2020-06-16 at 8 59 04 PM](https://user-images.githubusercontent.com/48804258/84816163-5deeff80-b014-11ea-8d50-1391d44ac0a1.png)
The original page 👇 
![Screen Shot 2020-06-16 at 8 59 10 PM](https://user-images.githubusercontent.com/48804258/84816167-5f202c80-b014-11ea-8ad6-88eec041a98d.png)

- [ ] On the small screen of the Featured slideshows section, the side images and text should be aligned in one line. The text should not wrap to the other line. Please compare your page with the original and fix this. 
The original page 👇 
![Screen Shot 2020-06-16 at 9 02 23 PM](https://user-images.githubusercontent.com/48804258/84817208-da81de00-b014-11ea-8b7f-47a39043b71c.png)
Your clone 👇 
![Screen Shot 2020-06-16 at 9 02 35 PM](https://user-images.githubusercontent.com/48804258/84817211-dbb30b00-b014-11ea-9ba6-133577890a74.png)

- [ ] The header for the subscribe and newsletter sections are missing.
- [ ] The newsletter on the medium screen size is not formatted properly. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-06-16 at 9 05 04 PM](https://user-images.githubusercontent.com/48804258/84817474-4e23eb00-b015-11ea-8277-852a3a088821.png)
![Screen Shot 2020-06-16 at 9 05 12 PM](https://user-images.githubusercontent.com/48804258/84817478-4f551800-b015-11ea-8ad4-6cfe5e42d1db.png)
The original page 👇 
![Screen Shot 2020-06-16 at 9 05 18 PM](https://user-images.githubusercontent.com/48804258/84817521-5f6cf780-b015-11ea-8479-56a2ef463d9f.png)

- [ ] The images in the subscribe section are not formatted properly on the small screen. 
The original page 👇 
![Screen Shot 2020-06-16 at 9 08 06 PM](https://user-images.githubusercontent.com/48804258/84817756-c9859c80-b015-11ea-8e81-92354f9eddaf.png)
Your clone 👇 
![Screen Shot 2020-06-16 at 9 08 13 PM](https://user-images.githubusercontent.com/48804258/84817790-d3a79b00-b015-11ea-9a09-da04495462ab.png)
![Screen Shot 2020-06-16 at 9 08 23 PM](https://user-images.githubusercontent.com/48804258/84817797-d5715e80-b015-11ea-99ec-287f08065fbe.png)

  - The two magazine covers should overlap

  - The magazine cover, text, and subscribe button are being partially cut off.

- [ ] There should be no image for the newsletter on the small screen. Please compare your clone with the original page and fix this. 
The original page 👇 
![Screen Shot 2020-06-16 at 9 13 07 PM](https://user-images.githubusercontent.com/48804258/84818137-4b75c580-b016-11ea-9fb7-b4c439b81025.png)
Your clone 👇 
![Screen Shot 2020-06-16 at 9 13 14 PM](https://user-images.githubusercontent.com/48804258/84818139-4c0e5c00-b016-11ea-9c88-9bd5f582f105.png)
### Footer

- [ ] The social media icons and the copyright text on the small screen are not properly aligned. Additionally, the text in the Editions sections extends beyond the width of the page. Please compare your clone with the original page and [...]

2020-06-16 19:20 UTC, BrittanyBlake commented on styles.css
> +}
Please try not to use `!important`

2020-06-16 19:20 UTC, BrittanyBlake commented on styles.css
> +  margin-right: -0.6rem !important;
Please try to minimize use of `!important`

2020-06-16 19:20 UTC, BrittanyBlake commented on styles.css
> +}
Please try to minimize use of `!important`

2020-06-16 19:21 UTC, BrittanyBlake commented on styles.css
> +  margin-left: -1.1rem !important;
Please try to minimize use of `!important`

2020-06-16 19:22 UTC, BrittanyBlake commented on styles.css
> +    text-transform: uppercase;
[OPTIONAL]- You can use the bootstrap class `text-uppercase` for this. Feel free to use [this cheatsheet](https://hackerthemes.com/bootstrap-cheatsheet/) for more information.

2020-06-16 19:22 UTC, BrittanyBlake commented on styles.css
> +  text-transform: uppercase;
[OPTIONAL]- You can use the bootstrap class `text-uppercase` for this. Feel free to use [this cheatsheet](https://hackerthemes.com/bootstrap-cheatsheet/) for more information.

2020-06-17 09:05 UTC, visva-dev commented
- Fixed navbar extends to the whole page.

2020-06-18 15:43 UTC, visva-dev commented
## Navigation Bar
- Fixed the navbar extends to the whole page
- Aligned search icon properly in the nav links
- Made nav bottom links to disappear until the large screen
## Main content
- Fixed horizontal scroll on md, lg screen sizes & too much white space problems
- Fixed styling of Debate and Opinion sections on md & sm screens
- Fixed editors section horizontal scroll & images stretch & title wrap on md screen
- Fixed featured slideshows section alignment on sm and md screens sizes
- Updated category styling
- Reduced using of !Important 
## Footer
- Fixed subscribe and newsletter section responsiveness

2020-06-18 17:55 UTC, rammazzoti2000 requested changes
### Hello @visva-dev :raised_hands: I am Alexandru Bangau, your code reviewer for this project :smile
Great job on this project and of course trying to implement the changes required by the previous TSE :1st_place_medal: .
There are still some issues that need to be fixed before approving this project, see the comments bellow :point_down: 
## :stop_sign: Required Changes :construction: :construction_worker: 
## Large Screen :desktop_computer: 
### Navbar:
- [ ] When resizing the links are not following the width of the container and as you can see from the screenshot the search input gets hidden away
![image](https://user-images.githubusercontent.com/3244654/85051380-b8fd2f80-b197-11ea-8886-89ad5488be15.png)
- [ ] It seems that the links in navbar are not taking the full width of the header container. As you can notice from the screenshot, there is also some alignment issues with the logo that is not centered and the buttons (login, subscribe) not align to the right.
#### Original:
![image](https://user-images.githubusercontent.com/3244654/85048651-e6e07500-b193-11ea-8a06-a6896151f30b.png)
#### Clone:
![image](https://user-images.githubusercontent.com/3244654/85048775-155e5000-b194-11ea-9730-ea840f7cc1b1.png)
- [ ] The debate and opinion still have too much space between the picture and the title description
#### Original:
![image](https://user-images.githubusercontent.com/3244654/85050035-c5808880-b195-11ea-9b5c-5725f438f75b.png)
#### Clone:
![image](https://user-images.githubusercontent.com/3244654/85049960-ad106e00-b195-11ea-9213-5937323c5e6d.png)
- [ ] More Stories section doesn't match properly, is missing the article content, you have the author instead.
#### Original:
![image](https://user-images.githubusercontent.com/3244654/85050365-43449400-b196-11ea-8b35-d2a630d445a9.png)
#### Clone: 
![image](https://user-images.githubusercontent.com/3244654/85050327-3162f100-b196-11ea-8b6d-a231861c4439.png)
- [ ] In the `In the Magazine` section you can notice the category labels(periscope/culture) are missing some padding, please add some
![image](https://user-images.githubusercontent.com/3244654/85050737-d1b91580-b196-11ea-8523-63232a82e41f.png)
- [ ] The right side articles on each specfic category is not quite as it supposed to be, you can compare it in the screenshots bellow
#### Original
![image](https://user-images.githubusercontent.com/3244654/85050965-2ceb0800-b197-11ea-9f51-6bbc9b00aac9.png)
#### Clone
![image](https://user-images.githubusercontent.com/3244654/85051006-3bd1ba80-b197-11ea-903f-cfe272f258c4.png)
- [ ] In the `Subscribe & Culture` section you can see that when resizing the content gets messed up this is usually when the child content doesn't follows the parent container, take a look
![image](https://user-images.githubusercontent.com/3244654/85051660-12655e80-b198-11ea-8cf1-1ab17906a794.png)

### Medium Screen
- [ ] The `Navbar` still presents some alignment issues with the `login, subscribe and hamburger menu`, they should properly align to the right
![image](https://user-images.githubusercontent.com/3244654/85052044-97507800-b198-11ea-8df3-0fb175aa53c4.png)
- [ ] In `The Debate` section you can see the thumb icon on the right is almost half hidden, see the screenshot bellow
![image](https://user-images.githubusercontent.com/3244654/85052239-de3e6d80-b198-11ea-98d3-1a611c0d27d5.png)
- [ ] The picture in the `Culture` section is not showing, while on the original page it does
#### Original
![image](https://user-images.githubusercontent.com/3244654/85052428-2eb5cb00-b199-11ea-8669-5fbb2e80ae37.png)
#### Clone 
![image](https://user-images.githubusercontent.com/3244654/85052456-3d03e700-b199-11ea-88dd-a076cf039968.png)
### Small Screen
- [ ] You can notice that the navbar still presents some issues, while the `Featured Stories` is the first content showing and the `Top Stories` is placed after it which is actually the wrong order. Also the label `US` should be placed on the bottom left corner
#### Original
![image](https://user-images.githubusercontent.com/3244654/85052898-fd89ca80-b199-11ea-8b3c-64dd470894a5.png)
#### Clone
![image](https://user-images.githubusercontent.com/3244654/85052865-eea31800-b199-11ea-912c-8073e9172bca.png)
- [ ] You have some sections, like `My Turn` and `Culture and travel` etc, that are taking the full with of the screen, instead they should keep the same margin lines with the rest of the page content. They also have the label not sticking to the bottom left corner where they actually belong to
![image](https://user-images.githubusercontent.com/3244654/85053318-96204a80-b19a-11ea-9ffd-91cb5155709d.png)
- [ ] Section `The Editor's Pick` and `In the Magazine` are not centered, you can see they align to the left, also the same problem here with the labels not stickink to the right spot
![image](https://user-images.githubusercontent.com/3244654/85053607-10e96580-b19b-11ea-9f3f-74c9ef300528.png)
- [ ] Here the main article picture is taking again the whole width, while the article bellow are taking only a portion
#### Original
![image](https://user-images.githubusercontent.com/3244654/85053886-79384700-b19b-11ea-935f-e4cef61eebb4.png)
#### Clone
![image](https://user-images.githubusercontent.com/3244654/85053830-61f95980-b19b-11ea-8660-e87c377ce1e9.png)
- [ ] Here the text is overflowing outside the main container
![image](https://user-images.githubusercontent.com/3244654/85054019-b43a7a80-b19b-11ea-9b66-b796040634d5.png)
 - [ ] The footer is not behaving like the original, see the screenshot below
#### Original
![image](https://user-images.githubusercontent.com/3244654/85054124-e2b85580-b19b-11ea-833c-674add9c6740.png)
#### Clone
![image](https://user-images.githubusercontent.com/3244654/85054103-d3390c80-b19b-11ea-8f3a-b5c6888b915c.png)

### :exclamation:  Note: 
Overall the project needs more improvements on the typography, like font-family styling, font-size, color etc.
Also if you compare the original project when hovering over anchor tags it will either be underlined or will change the color, yours it not doing that, not only once, mainly because in many places you didn't use anchor tags but either headers or paragraphs

### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of **_alexandru_** if you have any additional question)</em>
### :stop_sign: Status: Required Changes

2020-06-18 17:55 UTC, rammazzoti2000 commented on styles.css
> +}
No repeating code, you can notice all this classes are using the same font-family and most of them the same font-size, please refactor that.

2020-06-18 17:55 UTC, rammazzoti2000 commented on styles.css
> +}
Same as above

2020-06-18 17:55 UTC, rammazzoti2000 commented on styles.css
> +}
No repeating code, you can notice all this classes are using the same font-family and most of them the same font-size, please refactor that.

2020-06-20 10:49 UTC, visva-dev commented
## Issues fixed 
- Fixed bottom-nav styling for all screen sizes
- Fixed featured stories category styling
- Fixed all categories not sticking to the bottom problem
- Fixed More stories section alignment on all screens
- Updated responsiveness of debate and opinion sections
- Fixed right side articles styling
- Menu and subscribe sections updated style
- Fixed footer positioning
- Updated order
- Cleaned syntax with no repeating code approach

2020-06-20 11:17 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @visva-dev   :wave:
-
You have done a splendid job with the changes! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##

### Final Touches:

- Let's validate the markup HTML using this [tool](https://validator.w3.org/nu/#textarea) to remove the semantic errors.
- Let's update the live link of the page in the README file to reflect the new changes.
-  In the subscribe section, we have an issue. Refer to the screenshots below 👇  for comparison then tweak the small changes.
 
|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/visva-dev/PROJECT-USING-BOOTSTRAP/feature-branch/index.html)|
|:---:|:---:|
|![small-screen](https://user-images.githubusercontent.com/22345961/85200427-f250af00-b2ff-11ea-8d80-75ccb1e62304.png)|![small-screen-clone](https://user-images.githubusercontent.com/22345961/85200455-2b891f00-b300-11ea-863b-df2636a52476.png)|

-  Kindly reduce the sizes of the images a bit and centre the texts properly, thank you.

### OPTIONAL CHANGES.
- Improve the general colours of the page. They are currently a bit off. Let's see how they compare below and maybe try and work on that as well.

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/visva-dev/PROJECT-USING-BOOTSTRAP/feature-branch/index.html)|
|:---:|:---:|
|![source](https://user-images.githubusercontent.com/22345961/85200404-bf0e2000-b2ff-11ea-94b1-8e560faa5f4c.png)|![clone](https://user-images.githubusercontent.com/22345961/85200410-c6352e00-b2ff-11ea-9a33-4e9dc15d68de.png)|

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-20 13:40 UTC, visva-dev commented
## Changes made
- Fixed syntax errors
- Updated positioning of subscribe section
- Updated live dome link in the readme file

2020-06-20 13:51 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
***All the required tasks have been fulfilled in this project. Everything looks clean now. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @visva-dev! :+1:
- You can now merge this. I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-06-20 13:58 UTC, merged